# Generated by Django 5.2.5 on 2025-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default='2025-08-27'),
            preserve_default=False,
        ),
    ]
